# Generated by Django 3.1 on 2020-08-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/profiles/images/avatar.png', upload_to='avatars'),
        ),
    ]
