# Generated by Django 3.1 on 2020-08-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200810_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='.\\static\\profiles\\images\x07vatar.png', upload_to='avatars'),
        ),
    ]
